/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const HoverCardArrow: typeof import('@yi-ui/vue')['HoverCardArrow']
  const HoverCardContent: typeof import('@yi-ui/vue')['HoverCardContent']
  const HoverCardPortal: typeof import('@yi-ui/vue')['HoverCardPortal']
  const HoverCardRoot: typeof import('@yi-ui/vue')['HoverCardRoot']
  const HoverCardTrigger: typeof import('@yi-ui/vue')['HoverCardTrigger']
}
