/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FloatingUi: typeof import('./src/components/FloatingUi.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverCardArrow: typeof import('@yi-ui/vue')['HoverCardArrow']
    HoverCardContent: typeof import('@yi-ui/vue')['HoverCardContent']
    HoverCardPortal: typeof import('@yi-ui/vue')['HoverCardPortal']
    HoverCardRoot: typeof import('@yi-ui/vue')['HoverCardRoot']
    HoverCardTest: typeof import('./src/components/HoverCardTest.vue')['default']
    HoverCardTrigger: typeof import('@yi-ui/vue')['HoverCardTrigger']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
